### ISSUE TITLE
simple_xml_* functions may have errors phasing CDATA format xml?

### ISSUE THREAD

**Issue by jiaojie1989** [popphp/pop-data#1]
- http://stock.finance.sina.com.cn/usstock/view/360_api_v3.php?fn=us_360_1_1_3_4

This url has several CDATA sections which content may be a "http://" like url link.

I use pop\data like follows:

``` php
<?php
use Pop\Data as Data;
use Pop\Http as Http;

$getFunc = function($url) {
    $client = new Http\Client\Curl($url);
    $client->setReturnHeader(true)
            ->setReturnTransfer(true)
            ->send();
    return $client->getBody();
};
$unserializeXmlData = function($xmlData) {
    $xml = new Data\Data($xmlData);
    return $xml->unserialize();
};
$xmlData = $getFunc("http://stock.finance.sina.com.cn/usstock/view/360_api_v3.php?fn=us_360_1_1_3_4");
$unserializedXml = $unserializeXmlData($xmlData);
print_r($unserializedXml);
```

I got an array actually empty.

**Comment by nicksagona** [comment]
Hey, I'm trying to duplicate the issue over here, but I'm unable to. Can you share some sample XML data that is causing the issue for you so I can see if I can debug the issue using your sample XML data instead? Thanks.

**Comment by jiaojie1989** [comment]
Sample as follows,

``` xml
<display>
      <title><![CDATA[iShares追踪富时25中国股指数ETF[FXI]_美股实时行情_新浪财经]]></title>
      <url><![CDATA[http://stock.finance.sina.com.cn/usstock/quotes/FXI.html]]></url>
      <urlWap><![CDATA[http://stocks.sina.cn/us/?vt=4&code=FXI]]></urlWap>
      <stockNum><![CDATA[FXI]]></stockNum>
      <marketClosed><![CDATA[0]]></marketClosed>
      <Indexclosed><![CDATA[1]]></Indexclosed>
</display>
```

Just in the urlWap node. Thanks.

**Comment by nicksagona** [comment]
Ok thanks for getting me the sample XML. I was able to duplicate the issue and I believe I've patched the issue. I've tweaked the unserialize method to allow for LIBXML_\* options to be passed. If you do this:

``` php
$xml->unserialize(['options' => LIBXML_NOCDATA]);
```

it should get your the correct data. Update to v2.0.0p1 and let me know if that works for you.

Thanks

**Comment by jiaojie1989** [comment]
The patch works well after setting the `options`.
Thanks a lot.
